# Generated by Django 5.1.3 on 2024-12-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customuser_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
