# Generated by Django 5.1.3 on 2024-12-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
